safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html
relative_permalinks: false

default_theme: bright
default_width: 792
default_lang: ru
default_body_class: list

author:
    name: Копылов Егор
    # url:  http://example.com/
    company:
        name: Яндекс
        # url:  http://example.com/

fork_url: https://github.com/iEgit/bfs-ru
progress: true
line_numbers: true
